#!/bin/bash

set -o errexit
set -o nounset

# ADJUST THIS FOR YOUR SYSTEM
readonly DATABASE_DIR=${1:-/data/databases}

readonly CONTAINER_DB_DIR=/databases

if [ ! -d ${DATABASE_DIR} ]; then
    echo "Please create the database directory ${DATABASE_DIR} first."
    exit 2
fi

podman run \
    --volume ${DATABASE_DIR}:${CONTAINER_DB_DIR}:rw \
    --detach=false \
    --rm \
    --entrypoint /usr/local/bin/download-antismash-databases \
    docker.io/antismash/standalone-lite:7.1.0 \
        --data ${CONTAINER_DB_DIR}
