#!/bin/bash

set -o errexit
set -o nounset

if [ $# -lt 3 ]; then
    echo "Usage: $0 <distro> <buildcmdfile> <depfile>"
    exit 2
fi

readonly DISTRO=$1
readonly BUILDCMDFILE=$2
readonly DEPFILE=$3

# get a temporary directory
TMPDIR=$(mktemp -d)

function cleanup {
    rm -rf "$TMPDIR"
}
trap cleanup EXIT

cp "$BUILDCMDFILE" "$TMPDIR/buildcmd.sh"
cp "$DEPFILE" "$TMPDIR/depfile"

cat <<EOF >"$TMPDIR/run"
#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
cat /build/depfile | xargs apt-get install -y
bash /build/buildcmd.sh $DISTRO
EOF

chmod a+x "$TMPDIR/run"

docker run -it --rm -v "$(pwd)":/outside -v "$TMPDIR":/build kblin/${DISTRO}-fpm /build/run
