# Base image with all non-python dependencies for antiSMASH, even the non-OSS ones
# VERSION 7.0.0
FROM antismash/base:latest
LABEL maintainer="Kai Blin <kblin@biosustain.dtu.dk>"

# grab all the non-free dependencies
RUN apt-get update && \
    apt-get install -y \
        meme-suite \
        openmpi-bin \
    && \
    apt-get clean -y && \
    apt-get autoclean -y && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
