# antiSMASH build for the web service
# VERSION 2025050101
ARG ANTISMASH_VERSION
FROM docker.io/antismash/standalone-lite:${ANTISMASH_VERSION}
LABEL maintainer="Kai Blin <kblin@biosustain.dtu.dk>"

ADD run /usr/local/bin
