#!/bin/bash
set -o nounset

readonly INFILE=$1
shift

export MPLCONFIGDIR=/matplotlib

antismash $@ /input/${INFILE}
exitcode=$?

if [ $exitcode -ne 0 ]; then
    echo "Running antiSMASH FAILED"
    sleep 5
fi
exit $exitcode
